export const FightingClassesPreset = {
  range001: {
    classId: "range001",
    className: "Archer",
    baseStats: {
      hp: 10,
      mana: 0,
      atk: 1,
      mAtk: 1,
      def: 1,
      mDef: 1,
      agility: 1,
      dexterity: 1,
      speed: 1,
      luck: 1,
    },
    statsGrowingPotential: {
      hp: "A",
      mana: "A",
      atk: "A",
      mAtk: "A",
      def: "A",
      mDef: "A",
      agility: "A",
      dexterity: "A",
      speed: "A",
      luck: "A",
    },
    statsCapPotential: {
      hp: "A",
      mana: "A",
      atk: "A",
      mAtk: "A",
      def: "A",
      mDef: "A",
      agility: "A",
      dexterity: "A",
      speed: "A",
      luck: "A",
    },
  },
};
